spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.200.210.89:3306/vegetables?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root@123456a
  redis:
    host: 101.200.210.89
    database: 0
    port: 6379
    password:
  cache:
    cache-names: menus_cache
server:
  port: 8080
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  access-key-id: LTAI4G6iiVLeCeaY7nJjHVBw
  access-key-secret: nDksUXaqe7BOYcitathOnYtSfSYo40
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
#    endpoint: http://oss-cn-beijing-internal.aliyuncs.com
    bucket-name: vegetables-oss
#  用户登录名称 test@1300473727095366.onaliyun.com
#  AccessKey ID LTAI4G6iiVLeCeaY7nJjHVBw
#  AccessKey Secret nDksUXaqe7BOYcitathOnYtSfSYo40