spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/vegetables?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 101.200.210.89
    database: 0
    port: 6379
    password:
  cache:
    cache-names: menus_cache
server:
  port: 8080
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/

aliyun:
  access-key-id: LTAILRbN786aE1W4
  access-key-secret: GQ5msgueKw6xccaBqWzKG3dOf8gMiN
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    bucket-name: haitouhui-crm
